# -*- coding: utf-8 -*-
"""App_portafolioMV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJB0pqLoJ-GPyjDeflBLEKq8vLSfZH_b
"""

# Importamos las librerías
import streamlit as st
import pandas as pd
import yfinance as yf

st.title ("Mi primera aplicacion en Streamlit 🚀")

# Lista de ticker inicial
lista_tickers = ["AAPL", "MSFT", "NVDA","META"]

# Multiselector

ticker = st.multiselect("Elija un ticker", lista_tickers)

# Botón

if st.button("Descargar"):
  data=yf.download(ticker,period="1mo")["Close"]
  st.subheader("💸Precio de cierre")
  st.dataframe(data)

  st.subheader("📈Evolución del precio de cierre")
  st.line_chart(data)
else:
  st.warning("Selecciona al menos un ticker para continuar")