# -*- coding: utf-8 -*-
"""App_portafolioMV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJB0pqLoJ-GPyjDeflBLEKq8vLSfZH_b
"""

# Importamos las librerías
import streamlit as st
import pandas as pd

st.title ("Mi primera aplicacion en Streamlit 🚀")

